name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - name: Install deps
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Tests
              run: npm test -- --run

    patches:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_PASSWORD: postgres
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd "pg_isready -U postgres" --health-interval 5s --health-timeout 5s --health-retries 5
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
            - name: Install deps
              run: npm ci
            - name: Patch lint
              run: npm run lint:patches
            - name: Run migrate against local PG
              env:
                  POSTGRES_URL: postgresql://postgres:postgres@localhost:5432/postgres
                  POSTGRES_SSL: "false"
              run: npm run migrate
